trigger:
  branches:
    include:
      - main
      - feature/*

stages:
  - stage: terraform
    displayName: 'Terraform'
    jobs:
      - job: terraform
        displayName: 'Terraform'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        