on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for Azure login
  contents: read    # Required for actions/checkout

jobs:
  azlogin:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: 'Azure CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  tfinit:
    runs-on: ubuntu-latest
    environment: dev
    needs: azlogin

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt
        run: terraform -chdir=environment/dev fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=environment/dev init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=environment/dev validate -no-color

  tfplan:
    runs-on: ubuntu-latest
    environment: dev
    needs: tfinit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init
        id: init
        run: terraform -chdir=environment/dev init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=environment/dev plan -no-color
