on:
  push:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  azlogin:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
  terraform-init:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: azlogin
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: |
          terraform -chdir=environment/dev init
          terraform -chdir=environment/dev validate
          terraform -chdir=environment/dev plan
       
